# Generated by Django 4.2.2 on 2023-06-19 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='interest_provider',
            new_name='offering',
        ),
    ]
