# Generated by Django 4.2.2 on 2023-06-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_delete_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='offering',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
