# Generated by Django 4.2.2 on 2023-06-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_offering_interest_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='logo',
            field=models.ImageField(default='logos/default.png', upload_to='logos/'),
        ),
    ]
